"""customers, accounts, movements, compliance_alerts

Revision ID: 9a4fca016134
Revises: 4893449cf437
Create Date: 2026-09-28 16:26:08.498497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a4fca016134'
down_revision: Union[str, Sequence[str], None] = '4893449cf437'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('operator', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_operator'), 'customers', ['operator'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.String(length=34), nullable=False),
    sa.Column('customer_id', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_customer_id'), 'accounts', ['customer_id'], unique=False)
    op.create_table('compliance_alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(length=34), nullable=False),
    sa.Column('opened_by', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_compliance_alerts_account_id'), 'compliance_alerts', ['account_id'], unique=False)
    op.create_table('movements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(length=34), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movements_account_id'), 'movements', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movements_account_id'), table_name='movements')
    op.drop_table('movements')
    op.drop_index(op.f('ix_compliance_alerts_account_id'), table_name='compliance_alerts')
    op.drop_table('compliance_alerts')
    op.drop_index(op.f('ix_accounts_customer_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_customers_operator'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
