"""grafo

Revision ID: abfbe91ed812
Revises: 39c945daa688
Create Date: 2026-09-30 11:41:26.981793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abfbe91ed812'
down_revision: Union[str, Sequence[str], None] = '39c945daa688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph_estratti',
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('impronta', sa.String(length=64), nullable=False),
    sa.Column('relazioni', sa.Integer(), nullable=False),
    sa.Column('scartate', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('graph_nodes',
    sa.Column('chiave', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=32), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('chiave')
    )
    op.create_index(op.f('ix_graph_nodes_tipo'), 'graph_nodes', ['tipo'], unique=False)
    op.create_table('graph_revisione',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('chiave', sa.String(length=200), nullable=False),
    sa.Column('candidata', sa.String(length=200), nullable=False),
    sa.Column('somiglianza', sa.Float(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('stato', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chiave', 'candidata', name='uq_revisione')
    )
    op.create_index(op.f('ix_graph_revisione_chiave'), 'graph_revisione', ['chiave'], unique=False)
    op.create_table('graph_edges',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('da', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=32), nullable=False),
    sa.Column('a', sa.String(length=200), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('citazione', sa.Text(), nullable=False),
    sa.Column('visibility', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['a'], ['graph_nodes.chiave'], ),
    sa.ForeignKeyConstraint(['da'], ['graph_nodes.chiave'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('da', 'tipo', 'a', 'document_id', name='uq_arco')
    )
    op.create_index(op.f('ix_graph_edges_a'), 'graph_edges', ['a'], unique=False)
    op.create_index(op.f('ix_graph_edges_da'), 'graph_edges', ['da'], unique=False)
    op.create_index(op.f('ix_graph_edges_document_id'), 'graph_edges', ['document_id'], unique=False)
    op.create_index(op.f('ix_graph_edges_visibility'), 'graph_edges', ['visibility'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_graph_edges_visibility'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_document_id'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_da'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_a'), table_name='graph_edges')
    op.drop_table('graph_edges')
    op.drop_index(op.f('ix_graph_revisione_chiave'), table_name='graph_revisione')
    op.drop_table('graph_revisione')
    op.drop_index(op.f('ix_graph_nodes_tipo'), table_name='graph_nodes')
    op.drop_table('graph_nodes')
    op.drop_table('graph_estratti')
    # ### end Alembic commands ###
